name: Activity Box

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: JasonEtco/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: TobyDS
          GIST_ID: 27fce82a60db4f9d0ba962b9379d487e
